### ISSUE TITLE
Gurobi Settings

### ISSUE THREAD

**Issue by wilson-ricks** [GenXProject/GenX#26] opened 2021-06-16 21:34 UTC
configure_gurobi.jl does not include "Crossover" in the settings listed at line 68. This means that changing the "Crossover" tag in gurobi_settings.yml currently does nothing.

**Comment by GenXProject** [comment] 2021-06-22 23:14
Thanks @wilson-ricks  for pointing this out. This should be resolved in the latest commit.

**Comment by sambuddhac** [comment] 2021-06-24 00:21
@wilson-ricks can you please check now. I think the issue is resolved, as of yesterday, @GenXProject ?

**Closed** 2021-06-25 19:30 UTC
