### ISSUE TITLE
'Dimensions_graphic3' in docs is unreadable using Dark Mode

### ISSUE THREAD

**Issue by cfe316** [GenXProject/GenX#73] opened 2021-11-10 15:23 UTC
This uses black text on a transparent background, so when looking at a browser in Dark Mode it's not readable.
(I'll submit a PR to fix this shortly)

**Comment by cfe316** [comment] 2021-11-10 15:37
PR #75 fixes this.

**Comment by sambuddhac** [comment] 2021-11-12 18:20
The PR has been merged. The issue is fixed. Closing this.

**Closed** 2021-11-12 18:20 UTC
